name: Run Spring Boot Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Maven wrapper
        run: chmod +x ./mvnw

      - name: Force Maven to update dependencies
        run: ./mvnw --batch-mode --update-snapshots validate

      - name: Run tests
        run: ./mvnw test
